# Artificial Neural Networks
<hr>

## Part 1 - Importing dataset and data Pre-processing




In [1]:
import pandas as pd
import numpy as np

csv_url = "https://raw.githubusercontent.com/Bhavartha/Machine-Learning-A-Z/master/Part%208%20-%20Deep%20Learning/Section%2039%20-%20Artificial%20Neural%20Networks%20(ANN)/Churn_Modelling.csv"
dataset = pd.read_csv(csv_url)
dataset.head()

RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [2]:
# Separating Data into features and output

X = dataset.iloc[:,3:13].values
y = dataset['Exited']

X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [3]:
# Encoding categorial data

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer
ctX = ColumnTransformer([("encoder", OneHotEncoder(drop='first'), [1,2])], remainder = 'passthrough')
X = np.array(ctX.fit_transform(X),dtype=np.int)
X

array([[     0,      0,      0, ...,      1,      1, 101348],
       [     0,      1,      0, ...,      0,      1, 112542],
       [     0,      0,      0, ...,      1,      0, 113931],
       ...,
       [     0,      0,      0, ...,      0,      1,  42085],
       [     1,      0,      1, ...,      1,      0,  92888],
       [     0,      0,      0, ...,      1,      0,  38190]])

In [4]:
#Splitting in test and training
from sklearn.model_selection import train_test_split as TTS

X_train,X_test,y_train,y_test= TTS(X,y, test_size=0.2,random_state=0)
X_train

array([[     0,      1,      0, ...,      1,      0, 163830],
       [     1,      0,      1, ...,      1,      1,  57098],
       [     0,      0,      0, ...,      1,      0, 185630],
       ...,
       [     0,      0,      1, ...,      1,      0, 181429],
       [     0,      1,      0, ...,      1,      1, 148750],
       [     1,      0,      0, ...,      1,      0, 118855]])

In [5]:
# Feature Scaling

from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
ss.fit(X_train)
X_train=ss.transform(X_train)
X_test=ss.transform(X_test)

X_train

array([[-0.5698444 ,  1.74309049, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.10642907],
       [ 1.75486502, -0.57369368,  0.91601335, ...,  0.64259497,
         0.9687384 , -0.74865592],
       [-0.5698444 , -0.57369368, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.48532999],
       ...,
       [-0.5698444 , -0.57369368,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.41231335],
       [-0.5698444 ,  1.74309049, -1.09168714, ...,  0.64259497,
         0.9687384 ,  0.84432697],
       [ 1.75486502, -0.57369368, -1.09168714, ...,  0.64259497,
        -1.03227043,  0.32472867]])

## Part 2 - Creating ANN

In [6]:
# Importing keras libraries and packages

import keras
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [0]:
# Initializing ANN

classifier = Sequential()

# Adding input layer and first hidden layer
classifier.add(Dense(6,input_shape=(11,), activation='relu',kernel_initializer='uniform'))
# Adding second hidden layer and output layer
classifier.add(Dense(6, activation='relu',kernel_initializer='uniform'))
classifier.add(Dense(1, activation='sigmoid',kernel_initializer='uniform'))

In [0]:
# Compiling ANN

classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [11]:
# Fitting ANN

classifier.fit(X_train,y_train,batch_size=10,epochs=100)

Epoch 1/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3987 - accuracy: 0.8357
Epoch 2/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3989 - accuracy: 0.8347
Epoch 3/100
8000/8000 [==============================] - 1s 105us/step - loss: 0.3994 - accuracy: 0.8357
Epoch 4/100
8000/8000 [==============================] - 1s 106us/step - loss: 0.3989 - accuracy: 0.8360
Epoch 5/100
8000/8000 [==============================] - 1s 107us/step - loss: 0.3991 - accuracy: 0.8345
Epoch 6/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3986 - accuracy: 0.8353
Epoch 7/100
8000/8000 [==============================] - 1s 104us/step - loss: 0.3991 - accuracy: 0.8357
Epoch 8/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3994 - accuracy: 0.8344
Epoch 9/100
8000/8000 [==============================] - 1s 103us/step - loss: 0.3989 - accuracy: 0.8354
Epoch 10/100
8000/8000 [==============================]

## Part 3 - Predictions and evaluation of model

In [13]:
y_pred = classifier.predict(X_test)
y_pred = [1 if _>0.5 else 0 for _ in y_pred]

# Making confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1546,   49],
       [ 275,  130]])

In [14]:
(1546+130)/(1544+130+49+275)

0.8388388388388388